import { Amplify } from 'aws-amplify';
import outputs from '../../amplify_outputs.json';

// Call once at boot. `amplify_outputs.json` is generated by `npm run sandbox`.
// If you haven't deployed the sandbox yet, Auth / Data calls will no-op/fail.
export function configureAmplify() {
  Amplify.configure(outputs as never);
}
